#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 5000
#define TAPPING_TERM 250
#define PERMISSIVE_HOLD
#define COMBO_COUNT 7
#define COMBO_TERM 75
#define LEADER_TIMEOUT 500 
#define LEADER_PER_KEY_TIMING
